# This file is an example to demonstrate the usage of DSM CLI inside a GitHub pipeline
# Make sure to upload the executable and the configuration files to your project
# For more information on its usage, please visit https://docs.senhasegura.io/

name: senhasegura CLI CI/CD INSERT SECRET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  DJARRIN:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: PRUEBA INSERT SECRET
        run: echo Hello, world!
        
      - name: Run DSM CLI as Running Belt
        env:
          APPLICATION: ${{ secrets.APPLICATION }}
          SYSTEM: ${{ secrets.SYSTEM }}
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
        run: |
          chmod 777 dsm
          chmod 777 .config_insert.yaml
          chmod 777 senhasegura-mapping.json
          ./dsm runb --app-name $APPLICATION --system $SYSTEM --environment $ENVIRONMENT --config .config_insert.yaml --tool-name github
